local info=
{
	name = "Wanda Age Ticking(旺达年龄滴答声)",
	description = [[
此mod为旺达的老化增加了声音提示（变速滴答声）。

默认情况下，当旺达变老时，声音开始响起，当她可以治愈并保持老态时，声音会变得更快，最后在她垂死时，声音会变得疯狂——她只有很短的时间来承受所有的伤害。

如果配置了特定年龄，则以下内容必须始终为真，否则行为未定义：
时间记号1 < 时间记号2 < 时间记号3
	]],
	configuration_options = {
		{
			name = "TICK1",
			label = "时间记号1",
			options = {
				{description = "当变老的时候", data = 0},
				{description = "关闭", data = -1},
				{description = "20", data = 20},
				{description = "21", data = 21},
				{description = "22", data = 22},
				{description = "23", data = 23},
				{description = "24", data = 24},
				{description = "25", data = 25},
				{description = "26", data = 26},
				{description = "27", data = 27},
				{description = "28", data = 28},
				{description = "29", data = 29},
				{description = "30", data = 30},
				{description = "31", data = 31},
				{description = "32", data = 32},
				{description = "33", data = 33},
				{description = "34", data = 34},
				{description = "35", data = 35},
				{description = "36", data = 36},
				{description = "37", data = 37},
				{description = "38", data = 38},
				{description = "39", data = 39},
				{description = "40", data = 40},
				{description = "41", data = 41},
				{description = "42", data = 42},
				{description = "43", data = 43},
				{description = "44", data = 44},
				{description = "45", data = 45},
				{description = "46", data = 46},
				{description = "47", data = 47},
				{description = "48", data = 48},
				{description = "49", data = 49},
				{description = "50", data = 50},
				{description = "51", data = 51},
				{description = "52", data = 52},
				{description = "53", data = 53},
				{description = "54", data = 54},
				{description = "55", data = 55},
				{description = "56", data = 56},
				{description = "57", data = 57},
				{description = "58", data = 58},
				{description = "59", data = 59},
				{description = "60", data = 60},
				{description = "61", data = 61},
				{description = "62", data = 62},
				{description = "63", data = 63},
				{description = "64", data = 64},
				{description = "65", data = 65},
				{description = "66", data = 66},
				{description = "67", data = 67},
				{description = "68", data = 68},
				{description = "69", data = 69},
				{description = "70", data = 70},
				{description = "71", data = 71},
				{description = "72", data = 72},
				{description = "73", data = 73},
				{description = "74", data = 74},
				{description = "75", data = 75},
				{description = "76", data = 76},
				{description = "77", data = 77},
				{description = "78", data = 78},
				{description = "79", data = 79},
				{description = "80", data = 80}
			},
			default = 0
		},
		{
			name = "TICK2",
			label = "时间记号2",
			options = {
				{description = "变老并可以治愈时", data = 0},
				{description = "关闭", data = -1},
				{description = "20", data = 20},
				{description = "21", data = 21},
				{description = "22", data = 22},
				{description = "23", data = 23},
				{description = "24", data = 24},
				{description = "25", data = 25},
				{description = "26", data = 26},
				{description = "27", data = 27},
				{description = "28", data = 28},
				{description = "29", data = 29},
				{description = "30", data = 30},
				{description = "31", data = 31},
				{description = "32", data = 32},
				{description = "33", data = 33},
				{description = "34", data = 34},
				{description = "35", data = 35},
				{description = "36", data = 36},
				{description = "37", data = 37},
				{description = "38", data = 38},
				{description = "39", data = 39},
				{description = "40", data = 40},
				{description = "41", data = 41},
				{description = "42", data = 42},
				{description = "43", data = 43},
				{description = "44", data = 44},
				{description = "45", data = 45},
				{description = "46", data = 46},
				{description = "47", data = 47},
				{description = "48", data = 48},
				{description = "49", data = 49},
				{description = "50", data = 50},
				{description = "51", data = 51},
				{description = "52", data = 52},
				{description = "53", data = 53},
				{description = "54", data = 54},
				{description = "55", data = 55},
				{description = "56", data = 56},
				{description = "57", data = 57},
				{description = "58", data = 58},
				{description = "59", data = 59},
				{description = "60", data = 60},
				{description = "61", data = 61},
				{description = "62", data = 62},
				{description = "63", data = 63},
				{description = "64", data = 64},
				{description = "65", data = 65},
				{description = "66", data = 66},
				{description = "67", data = 67},
				{description = "68", data = 68},
				{description = "69", data = 69},
				{description = "70", data = 70},
				{description = "71", data = 71},
				{description = "72", data = 72},
				{description = "73", data = 73},
				{description = "74", data = 74},
				{description = "75", data = 75},
				{description = "76", data = 76},
				{description = "77", data = 77},
				{description = "78", data = 78},
				{description = "79", data = 79},
				{description = "80", data = 80}
			},
			default = 0
		},
		{
			name = "TICK3",
			label = "时间记号3",
			options = {
				{description = "技术上死亡", data = 0},
				{description = "关闭", data = -1},
				{description = "20", data = 20},
				{description = "21", data = 21},
				{description = "22", data = 22},
				{description = "23", data = 23},
				{description = "24", data = 24},
				{description = "25", data = 25},
				{description = "26", data = 26},
				{description = "27", data = 27},
				{description = "28", data = 28},
				{description = "29", data = 29},
				{description = "30", data = 30},
				{description = "31", data = 31},
				{description = "32", data = 32},
				{description = "33", data = 33},
				{description = "34", data = 34},
				{description = "35", data = 35},
				{description = "36", data = 36},
				{description = "37", data = 37},
				{description = "38", data = 38},
				{description = "39", data = 39},
				{description = "40", data = 40},
				{description = "41", data = 41},
				{description = "42", data = 42},
				{description = "43", data = 43},
				{description = "44", data = 44},
				{description = "45", data = 45},
				{description = "46", data = 46},
				{description = "47", data = 47},
				{description = "48", data = 48},
				{description = "49", data = 49},
				{description = "50", data = 50},
				{description = "51", data = 51},
				{description = "52", data = 52},
				{description = "53", data = 53},
				{description = "54", data = 54},
				{description = "55", data = 55},
				{description = "56", data = 56},
				{description = "57", data = 57},
				{description = "58", data = 58},
				{description = "59", data = 59},
				{description = "60", data = 60},
				{description = "61", data = 61},
				{description = "62", data = 62},
				{description = "63", data = 63},
				{description = "64", data = 64},
				{description = "65", data = 65},
				{description = "66", data = 66},
				{description = "67", data = 67},
				{description = "68", data = 68},
				{description = "69", data = 69},
				{description = "70", data = 70},
				{description = "71", data = 71},
				{description = "72", data = 72},
				{description = "73", data = 73},
				{description = "74", data = 74},
				{description = "75", data = 75},
				{description = "76", data = 76},
				{description = "77", data = 77},
				{description = "78", data = 78},
				{description = "79", data = 79},
				{description = "80", data = 80}
			},
			default = 0
		}
	}
}
return info