local Keys = {
	{description = "无 --", data = -1}, -- 如果玩家找不到“无”选项
	{description = "小键盘 0", data = 256},
	{description = "小键盘 1", data = 257},
	{description = "小键盘 2", data = 258},
	{description = "小键盘 3", data = 259},
	{description = "小键盘 4", data = 260},
	{description = "小键盘 5", data = 261},
	{description = "小键盘 6", data = 262},
	{description = "小键盘 7", data = 263},
	{description = "小键盘 8", data = 264},
	{description = "小键盘 9", data = 265},
	{description = "小键盘 .", data = 266},
	{description = "小键盘 /", data = 267},
	{description = "小键盘 *", data = 268},
	{description = "小键盘 -", data = 269},
	{description = "小键盘 +", data = 270},
--	{description = "小键盘 Enter", data = 271},
--	{description = "小键盘 =", data = 272},
	{description = "↑", data = 273},
	{description = "↓", data = 274},
	{description = "←", data = 276},
	{description = "→", data = 275},
	{description = "-", data = 45},
	{description = "+", data = 43},
	{description = "(", data = 91},
	{description = ")", data = 93},
	{description = ";", data = 59},
	{description = "\'", data = 39},
	{description = ",", data = 44},
	{description = ".", data = 46},
	{description = "/", data = 47},
	{description = "PageUp", data = 280},
	{description = "PageDown", data = 281},
	{description = "Home", data = 278},
	{description = "End", data = 279},
	{description = "Insert", data = 277},
	{description = "Delete", data = 127},
	{description = "-- 无 --", data = 0}, -- 在这里不放任何东西可以帮助其他人设置按键
	{description = "A", data = 97},
	{description = "B", data = 98},
	{description = "C", data = 99},
	{description = "D", data = 100},
	{description = "E", data = 101},
	{description = "F", data = 102},
	{description = "G", data = 103},
	{description = "H", data = 104},
	{description = "I", data = 105},
	{description = "J", data = 106},
	{description = "K", data = 107},
	{description = "L", data = 108},
	{description = "M", data = 109},
	{description = "N", data = 110},
	{description = "O", data = 111},
	{description = "P", data = 112},
	{description = "Q", data = 113},
	{description = "R", data = 114},
	{description = "S", data = 115},
	{description = "T", data = 116},
	{description = "U", data = 117},
	{description = "V", data = 118},
	{description = "W", data = 119},
	{description = "X", data = 120},
	{description = "Y", data = 121},
	{description = "Z", data = 122},
	{description = "F1", data = 282},
	{description = "F2", data = 283},
	{description = "F3", data = 284},
	{description = "F4", data = 285},
	{description = "F5", data = 286},
	{description = "F6", data = 287},
	{description = "F7", data = 288},
	{description = "F8", data = 289},
	{description = "F9", data = 290},
	{description = "F10", data = 291},
	{description = "F11", data = 292},
	{description = "F12", data = 293},
	{description = "-- 无", data = -1}, -- 为了避免迫使玩家一直点击回到开头
}

local info=
{
	name="Bone Helm Shadow Toggle(骨盔阴影切换)",
	description="装备骨盔后，可以关闭影怪显示",
	configuration_options =
	{
		{
			name = "buttonEnabled",
			label = "启用按钮",
			options =
			{
				{description = "是", data = true},
				{description = "否", data = false},

			},
			default = true,
		},
		{
			name = "keybind",
			label = "开关快捷键",
			options = Keys,
			default = 0,
		}
	}
}
return info