local info=
{
  name = "Adventure Mode(冒险模式)",
  description = "需要我的 Teleportato(世界折跃) 模组！\n\n战胜充满挑战的世界，一个接一个的饥荒冒险模式！\n\n此模组和 Teleportato(世界折跃)的模组设置一起工作，因此不要忘记根据您的喜好调整两者\n\n这个mod覆盖了Teleportato(世界折跃) 模组中的远古科学站、玄武岩、三维数值、新世界 设置，因此这些设置不会在那里做任何事情\n\n如果您愿意，您可以在游戏设置屏幕中更改世界生成后的季节/日长度和其他世界设置",
  configuration_options =
  {
    {
      name = "experimentalcode",
      label = "测试代码",
      hover = "如果您想测试可能包含错误的新功能，请启用(目前没有)",
      options =
      {
              {description = "关闭", data = false, hover=""},
              {description = "开启", data = true, hover=""},
          },
      default = false,
      },
      {
        name = "",
        label = "",
        hover = "",
        options =	{
                {description = "", data = 0},
              },
        default = 0,
      },
      {
      name = "difficulty",
      label = "难度",
      hover = "您也可以将此设置为DS（单机版难度）！不要为了速通游戏而改变这个",
      options =
      {
        {description = "DS（单机版）", data = 0, hover="只有必要的更改在大多数情况下，这将与单机版冒险模式相同"},
              {description = "容易", data = 1, hover="更多初始物品，轻松冒险"},
              {description = "中等", data = 2, hover="适度的初始物品，正常的冒险"},
              {description = "困难", data = 3, hover="初始物品很少，这是一次艰难的冒险！"}, -- 许多代码依赖于这些值0-3，因此在不调整所有代码的情况下不要更改或添加这些值！
          },
      default = 2,
      },
      {
      name = "sandboxpreconfigured",
      label = "定制麦斯威尔之门",
      hover = "第一个级别“麦斯威尔之门”是否取决于您的世界设置或预配置？",
      options =
      {
              {description = "世界设置", data = false, hover="生成您的自定义世界设置并将麦斯威尔之门放置在某处。（来自Teleportato的“改变世界”不起作用）"},
              {description = "预配置", data = true, hover="生成一个小小的沼泽世界，你会很快找到入口并开始冒险"},
          },
      default = true,
      },
      {
      name = "repickcharacter",
      label = "重选角色",
      hover = "跳跃世界后的角色？如果禁用，您将不会收到第2章及以后的初始物品",
      options =
      {
              {description = "不重新挑选", data = false, hover="对于第2章及以后的章节，始终使用相同的角色且没有初始物品"},
              {description = "重新挑选", data = true, hover="每次都能重新挑选角色并获得初始物品"},
          },
      default = false,
      },
      {
      name = "withocean",
      label = "海洋？",
      hover = "是否可以制作智囊团？（虫洞只会在岛屿生成）",
      options =
      {
              {description = "只有虫洞", data = "wormholes", hover="船被禁用，使用虫洞，就像在单机版中一样"},
              {description = "仅海洋", data = "ocean", hover="有海洋，没有虫洞，所以你必须使用船"},
              {description = "海洋和虫洞", data = "oceanwormholes", hover="有海洋和虫洞，所以你也可以使用船"},
          },
      default = "oceanwormholes",
      },
      {
      name = "null_option",
      label = "",
      hover = "",
      options =	{
              {description = "", data = 0},
            },
      default = 0,
      },
      {
      name = "worldsizeacoldreception",
      label = "冷淡的接待-世界大小",
      hover = "冷淡的接待的世界尺寸",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "小", data = "small", hover="无法在PS4上工作"},
              {description = "中等", data = "medium", hover=""},
              {description = "大", data = "default", hover=""},
              {description = "巨大", data = "huge", hover="无法在PS4上工作"},
          },
      default = false,
      },
      {
      name = "startseasonacoldreception",
      label = "冷淡的接待-开始季节",
      hover = "冷淡的接待世界的开始季节。如果季节设定为秋季，则为10天",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "秋季", data = "default", hover=""},
              {description = "冬季", data = "winter", hover=""},
              {description = "春季", data = "spring", hover=""},
              {description = "夏季", data = "summer", hover=""},
              {description = "秋季或春季", data = "autumn|spring", hover=""},
              {description = "冬季或夏季", data = "winter|summer", hover=""},
              {description = "随机", data = "autumn|winter|spring|summer", hover=""},
          },
      default = false,
      },
      {
      name = "autumnacoldreception",
      label = "冷淡的接待-秋季",
      hover = "冷淡的接待中的秋季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "winteracoldreception",
      label = "冷淡的接待-冬季",
      hover = "冷淡的接待中的冬季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "springacoldreception",
      label = "冷淡的接待-春季",
      hover = "冷淡的接待中的春季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "summeracoldreception",
      label = "冷淡的接待-夏季",
      hover = "冷淡的接待中的夏季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "dayacoldreception",
      label = "冷淡的接待-一天",
      hover = "冷淡的接待中的日长度",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "正常的", data = "default", hover=""},
              {description = "长-白天", data = "longday", hover=""},
              {description = "长-黄昏", data = "longdusk", hover=""},
              {description = "长-夜晚", data = "longnight", hover=""},
              {description = "无白天", data = "noday", hover=""},
              {description = "无黄昏", data = "nodusk", hover=""},
              {description = "无夜晚", data = "nonight", hover=""},
              {description = "仅白天", data = "onlyday", hover=""},
              {description = "仅黄昏", data = "onlydusk", hover=""},
              {description = "仅夜晚", data = "onlynight", hover=""},

          },
      default = false,
      },
      {
      name = "worldsizekingofwinter",
      label = "冬季之王-世界大小",
      hover = "冬季之王的世界尺寸",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "小", data = "small", hover="无法在PS4上工作"},
              {description = "中等", data = "medium", hover=""},
              {description = "大", data = "default", hover=""},
              {description = "巨大", data = "huge", hover="无法在PS4上工作"},
          },
      default = false,
      },
      {
      name = "startseasonkingofwinter",
      label = "冬季之王-开始季节",
      hover = "冬季之王的开始季节。如果季节设定为秋季，则为10天",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "秋季", data = "default", hover=""},
              {description = "冬季", data = "winter", hover=""},
              {description = "春季", data = "spring", hover=""},
              {description = "夏季", data = "summer", hover=""},
              {description = "秋季或春季", data = "autumn|spring", hover=""},
              {description = "冬季或夏季", data = "winter|summer", hover=""},
              {description = "随机", data = "autumn|winter|spring|summer", hover=""},
          },
      default = false,
      },
      {
      name = "autumnkingofwinter",
      label = "冬季之王-秋季",
      hover = "冬季之王中的秋季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "winterkingofwinter",
      label = "冬季之王-冬季",
      hover = "冬季之王中的冬季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "springkingofwinter",
      label = "冬季之王-春季",
      hover = "冬季之王中的春季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "summerkingofwinter",
      label = "冬季之王-夏季",
      hover = "冬季之王中的夏季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "daykingofwinter",
      label = "冬季之王-一天",
      hover = "冬季之王中的日长度",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "正常", data = "default", hover=""},
              {description = "长-白天", data = "longday", hover=""},
              {description = "长-黄昏", data = "longdusk", hover=""},
              {description = "长-夜晚", data = "longnight", hover=""},
              {description = "无白天", data = "noday", hover=""},
              {description = "无黄昏", data = "nodusk", hover=""},
              {description = "无夜晚", data = "nonight", hover=""},
              {description = "仅白天", data = "onlyday", hover=""},
              {description = "仅黄昏", data = "onlydusk", hover=""},
              {description = "仅夜晚", data = "onlynight", hover=""},

          },
      default = false,
      },
      {
      name = "worldsizethegameisafoot",
      label = "游戏进行中-世界大小",
      hover = "游戏进行中的世界尺寸",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "小", data = "small", hover="无法在PS4上工作"},
              {description = "中等", data = "medium", hover=""},
              {description = "大", data = "default", hover=""},
              {description = "巨大", data = "huge", hover="无法在PS4上工作"},
          },
      default = false,
      },
      {
      name = "startseasonthegameisafoot",
      label = "游戏进行中-开始季节",
      hover = "游戏进行中的开始季节。如果季节设定为秋季，则为10天",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "秋季", data = "default", hover=""},
              {description = "冬季", data = "winter", hover=""},
              {description = "春季", data = "spring", hover=""},
              {description = "夏季", data = "summer", hover=""},
              {description = "秋季或春季", data = "autumn|spring", hover=""},
              {description = "冬季或夏季", data = "winter|summer", hover=""},
              {description = "随机", data = "autumn|winter|spring|summer", hover=""},
          },
      default = false,
      },
      {
      name = "autumnthegameisafoot",
      label = "游戏进行中-秋季",
      hover = "游戏进行中的秋季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "winterthegameisafoot",
      label = "游戏进行中-冬季",
      hover = "游戏进行中的冬季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "springthegameisafoot",
      label = "游戏进行中-春季",
      hover = "游戏进行中的春季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "summerthegameisafoot",
      label = "游戏进行中-夏季",
      hover = "游戏进行中的夏季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "daythegameisafoot",
      label = "游戏进行中-一天",
      hover = "游戏进行中的日长度",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "正常", data = "default", hover=""},
              {description = "长-白天", data = "longday", hover=""},
              {description = "长-黄昏", data = "longdusk", hover=""},
              {description = "长-夜晚", data = "longnight", hover=""},
              {description = "无白天", data = "noday", hover=""},
              {description = "无黄昏", data = "nodusk", hover=""},
              {description = "无夜晚", data = "nonight", hover=""},
              {description = "仅白天", data = "onlyday", hover=""},
              {description = "仅黄昏", data = "onlydusk", hover=""},
              {description = "仅夜晚", data = "onlynight", hover=""},

          },
      default = false,
      },
      {
      name = "worldsizearchipelago",
      label = "群岛-世界大小",
      hover = "群岛的世界尺寸",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "小", data = "small", hover="无法在PS4上工作"},
              {description = "中等", data = "medium", hover=""},
              {description = "大", data = "default", hover=""},
              {description = "巨大", data = "huge", hover="无法在PS4上工作"},
          },
      default = false,
      },
      {
      name = "startseasonarchipelago",
      label = "群岛-开始季节",
      hover = "群岛的开始季节。如果季节设定为秋季，则为10天",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "秋季", data = "default", hover=""},
              {description = "冬季", data = "winter", hover=""},
              {description = "春季", data = "spring", hover=""},
              {description = "夏季", data = "summer", hover=""},
              {description = "秋季或春季", data = "autumn|spring", hover=""},
              {description = "冬季或夏季", data = "winter|summer", hover=""},
              {description = "随机", data = "autumn|winter|spring|summer", hover=""},
          },
      default = false,
      },
      {
      name = "autumnarchipelago",
      label = "群岛-秋季",
      hover = "群岛中的秋季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "winterarchipelago",
      label = "群岛-冬季",
      hover = "群岛中的冬季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "springarchipelago",
      label = "群岛-春季",
      hover = "群岛中的春季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "summerarchipelago",
      label = "群岛-夏季",
      hover = "群岛中的夏季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "dayarchipelago",
      label = "群岛-一天",
      hover = "群岛中的日长度",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "正常", data = "default", hover=""},
              {description = "长-白天", data = "longday", hover=""},
              {description = "长-黄昏", data = "longdusk", hover=""},
              {description = "长-夜晚", data = "longnight", hover=""},
              {description = "无白天", data = "noday", hover=""},
              {description = "无黄昏", data = "nodusk", hover=""},
              {description = "无夜晚", data = "nonight", hover=""},
              {description = "仅白天", data = "onlyday", hover=""},
              {description = "仅黄昏", data = "onlydusk", hover=""},
              {description = "仅夜晚", data = "onlynight", hover=""},

          },
      default = false,
      },
      {
      name = "worldsizetwoworlds",
      label = "两个世界-世界大小",
      hover = "两个世界的世界尺寸",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "小", data = "small", hover="无法在PS4上工作"},
              {description = "中等", data = "medium", hover=""},
              {description = "大", data = "default", hover=""},
              {description = "巨大", data = "huge", hover="无法在PS4上工作"},
          },
      default = false,
      },
      {
      name = "startseasontwoworlds",
      label = "两个世界-开始季节",
      hover = "两个世界的开始季节。如果季节设定为秋季，则为10天",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "秋季", data = "default", hover=""},
              {description = "冬季", data = "winter", hover=""},
              {description = "春季", data = "spring", hover=""},
              {description = "夏季", data = "summer", hover=""},
              {description = "秋季或春季", data = "autumn|spring", hover=""},
              {description = "冬季或夏季", data = "winter|summer", hover=""},
              {description = "随机", data = "autumn|winter|spring|summer", hover=""},
          },
      default = false,
      },
      {
      name = "autumntwoworlds",
      label = "两个世界-秋季",
      hover = "两个世界中的秋季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "wintertwoworlds",
      label = "两个世界-冬季",
      hover = "两个世界中的冬季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "springtwoworlds",
      label = "两个世界-春季",
      hover = "两个世界中的春季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "summertwoworlds",
      label = "两个世界-夏季",
      hover = "两个世界中的夏季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "daytwoworlds",
      label = "两个世界-一天",
      hover = "两个世界中的日长度",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "正常", data = "default", hover=""},
              {description = "长-白天", data = "longday", hover=""},
              {description = "长-黄昏", data = "longdusk", hover=""},
              {description = "长-夜晚", data = "longnight", hover=""},
              {description = "无白天", data = "noday", hover=""},
              {description = "无黄昏", data = "nodusk", hover=""},
              {description = "无夜晚", data = "nonight", hover=""},
              {description = "仅白天", data = "onlyday", hover=""},
              {description = "仅黄昏", data = "onlydusk", hover=""},
              {description = "仅夜晚", data = "onlynight", hover=""},

          },
      default = false,
      },
      {
      name = "worldsizedarkness",
      label = "黑暗-世界大小",
      hover = "黑暗的世界尺寸",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "小", data = "small", hover="无法在PS4上工作"},
              {description = "中等", data = "medium", hover=""},
              {description = "大", data = "default", hover=""},
              {description = "巨大", data = "huge", hover="无法在PS4上工作"},
          },
      default = false,
      },
      {
      name = "startseasondarkness",
      label = "黑暗-开始季节",
      hover = "黑暗中的开始季节。如果季节设定为秋季，则为10天",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "秋季", data = "default", hover=""},
              {description = "冬季", data = "winter", hover=""},
              {description = "春季", data = "spring", hover=""},
              {description = "夏季", data = "summer", hover=""},
              {description = "秋季或春季", data = "autumn|spring", hover=""},
              {description = "冬季或夏季", data = "winter|summer", hover=""},
              {description = "随机", data = "autumn|winter|spring|summer", hover=""},
          },
      default = false,
      },
      {
      name = "autumndarkness",
      label = "黑暗-秋季",
      hover = "黑暗中的秋季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "winterdarkness",
      label = "黑暗-冬季",
      hover = "黑暗中的冬季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "springdarkness",
      label = "黑暗-春季",
      hover = "黑暗中的春季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "summerdarkness",
      label = "黑暗-夏季",
      hover = "黑暗中的夏季",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "无", data = "noseason", hover=""},
              {description = "非常短的季节", data = "veryshortseason", hover=""},
              {description = "短季节", data = "shortseason", hover=""},
              {description = "中等", data = "default", hover=""},
              {description = "漫长的季节", data = "longseason", hover=""},
              {description = "非常长的季节", data = "verylongseason", hover=""},
              {description = "随机", data = "random", hover=""},
          },
      default = false,
      },
      {
      name = "daydarkness",
      label = "黑暗-一天",
      hover = "黑暗中的日长度",
      options =
      {
              {description = "默认", data = false, hover="此mod的默认值"},
              {description = "正常", data = "default", hover=""},
              {description = "长-白天", data = "longday", hover=""},
              {description = "长-黄昏", data = "longdusk", hover=""},
              {description = "长-夜晚", data = "longnight", hover=""},
              {description = "无白天", data = "noday", hover=""},
              {description = "无黄昏", data = "nodusk", hover=""},
              {description = "无夜晚", data = "nonight", hover=""},
              {description = "仅白天", data = "onlyday", hover=""},
              {description = "仅黄昏", data = "onlydusk", hover=""},
              {description = "仅夜晚", data = "onlynight", hover=""},

          },
      default = false,
      },
      {
      name = "null_option",
      label = "",
      hover = "",
      options =	{
              {description = "", data = 0},
            },
      default = 0,
    },
      {
      name = "maxwellsdoor",
      label = "麦斯威尔之门",
      hover = "启用/禁用 默认冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但您必须启用另一个起始地图，否则将加载一个随机起始地图"},
              {description = "开启", data = "1", hover="将此世界加载为起始地图"},
          },
      default = "1",
      },
      {
      name = "acoldreception",
      label = "冷淡的接待",
      hover = "启用/禁用 冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但如果没有足够多的世界处于开启状态，则会加载随机的世界，即使它们被禁用"},
              {description = "2", data = "2", hover="\n"},
              {description = "3", data = "3", hover="\n"},
              {description = "4", data = "4", hover="\n"},
              {description = "5", data = "5", hover="\n"},
              {description = "2,3,4", data = "2,3,4", hover="在2到4之间随机选择"},
              {description = "2,3", data = "2,3", hover="\n"},
              {description = "2,4", data = "2,4", hover="\n"},
              {description = "2,5", data = "2,5", hover="\n"},
              {description = "3,4", data = "3,4", hover="\n"},
              {description = "3,5", data = "3,5", hover="\n"},
              {description = "4,5", data = "4,5", hover="\n"},
              {description = "2,3,4,5", data = "2,3,4,5", hover="\n"},
              {description = "3,4,5", data = "3,4,5", hover="\n"},
              {description = "2,4,5", data = "2,4,5", hover="\n"},
              {description = "2,3,5", data = "2,3,5", hover="\n"},
          },
      default = "2,3,4",
      },
      {
      name = "kingofwinter",
      label = "冬季之王",
      hover = "启用/禁用 冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但如果没有足够多的世界处于开启状态，则会加载随机的世界，即使它们被禁用"},
              {description = "2", data = "2", hover="\n"},
              {description = "3", data = "3", hover="\n"},
              {description = "4", data = "4", hover="\n"},
              {description = "5", data = "5", hover="\n"},
              {description = "2,3,4,5", data = "2,3,4,5", hover="在2到5之间随机选择"},
              {description = "2,3", data = "2,3", hover="\n"},
              {description = "2,4", data = "2,4", hover="\n"},
              {description = "2,5", data = "2,5", hover="\n"},
              {description = "3,4", data = "3,4", hover="\n"},
              {description = "3,5", data = "3,5", hover="\n"},
              {description = "4,5", data = "4,5", hover="\n"},
              {description = "2,3,4", data = "2,3,4", hover="\n"},
              {description = "3,4,5", data = "3,4,5", hover="\n"},
              {description = "2,4,5", data = "2,4,5", hover="\n"},
              {description = "2,3,5", data = "2,3,5", hover="\n"},
          },
      default = "2,3,4,5",
      },
      {
      name = "thegameisafoot",
      label = "游戏进行中",
      hover = "启用/禁用 冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但如果没有足够多的世界处于开启状态，则会加载随机的世界，即使它们被禁用"},
              {description = "2", data = "2", hover="\n"},
              {description = "3", data = "3", hover="\n"},
              {description = "4", data = "4", hover="\n"},
              {description = "5", data = "5", hover="\n"},
              {description = "2,3,4,5", data = "2,3,4,5", hover="在2到5之间随机选择"},
              {description = "2,3", data = "2,3", hover="\n"},
              {description = "2,4", data = "2,4", hover="\n"},
              {description = "2,5", data = "2,5", hover="\n"},
              {description = "3,4", data = "3,4", hover="\n"},
              {description = "3,5", data = "3,5", hover="\n"},
              {description = "4,5", data = "4,5", hover="\n"},
              {description = "2,3,4", data = "2,3,4", hover="\n"},
              {description = "3,4,5", data = "3,4,5", hover="\n"},
              {description = "2,4,5", data = "2,4,5", hover="\n"},
              {description = "2,3,5", data = "2,3,5", hover="\n"},
          },
      default = "2,3,4,5",
      },
      {
      name = "archipelago",
      label = "群岛",
      hover = "启用/禁用 冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但如果没有足够多的世界处于开启状态，则会加载随机的世界，即使它们被禁用"},
              {description = "2", data = "2", hover="\n"},
              {description = "3", data = "3", hover="\n"},
              {description = "4", data = "4", hover="\n"},
              {description = "5", data = "5", hover="\n"},
              {description = "2,3,4,5", data = "2,3,4,5", hover="在2到5之间随机选择"},
              {description = "2,3", data = "2,3", hover="\n"},
              {description = "2,4", data = "2,4", hover="\n"},
              {description = "2,5", data = "2,5", hover="\n"},
              {description = "3,4", data = "3,4", hover="\n"},
              {description = "3,5", data = "3,5", hover="\n"},
              {description = "4,5", data = "4,5", hover="\n"},
              {description = "2,3,4", data = "2,3,4", hover="\n"},
              {description = "3,4,5", data = "3,4,5", hover="\n"},
              {description = "2,4,5", data = "2,4,5", hover="\n"},
              {description = "2,3,5", data = "2,3,5", hover="\n"},
          },
      default = "2,3,4,5",
      },
      {
      name = "twoworlds",
      label = "两个世界",
      hover = "启用/禁用 冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但如果没有足够多的世界处于开启状态，则会加载随机的世界，即使它们被禁用"},
              {description = "4", data = "4", hover="\n"},
              {description = "5", data = "5", hover="\n"},
              {description = "4,5", data = "4,5", hover="在4到5之间随机选择"},
          },
      default = "4,5",
      },
      {
      name = "darkness",
      label = "黑暗",
      hover = "启用/禁用 冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但您必须启用另一个第六世界，否则将加载一个随机的第六世界"},
              {description = "6", data = "6", hover="将此世界加载为第六张地图"},
          },
      default = "6",
      },
      {
      name = "checkmate",
      label = "尾声-挫败",
      hover = "启用/禁用 冒险世界\n您还可以设置它们开始的位置",
      options =
      {
              {description = "关闭", data = "", hover="不要加载这个世界。但您必须启用另一个结尾世界，否则将加载一个随机结尾世界"},
              {description = "7", data = "7", hover="将此世界加载为结束地图"},
          },
      default = "7",
      },
  }
}
return info