local info={
	name = "Teleportato(世界折跃)",
	description =
[[
在世界生成时添加传送基座部分，并使探测杖可制造。
在mod的设置中，你可以选择应该发生什么。传送基座完成时，如果激活，是否应该生成一个新的世界。
最好不要将这个mod添加到已经生成的世界中，如果你在世界生成时激活了它，也不要停用它！
管理员可以使用say命令 /worldjump 来生成新世界。洞穴里玩家的东西不会被保存（除非你激活了GEMAPI）！
其他MOD也可以添加到冒险世界！
]],
	configuration_options =
	{
		{
			name = "variateworld",
			label = "改变世界",
			hover = "在世界生成时随机选择世界设置，您的世界设置将无效！使用模组 “Increase Animals”获得更多样化的体验。",
			options =	{
							{description = "否", data = false, hover = "总是选择相同的世界设置"},
							{description = "仅岛屿", data = "justislands", hover = "没有变化，但下面的 岛屿数量/变量事件 选项有效"},
							{description = "是,混合世界", data = true, hover = "中等难度，但易/难方面的机会较小"},
							{description = "是,简单的世界", data = "easy", hover = " "},
							{description = "是,中等世界", data = "medium", hover = " "},
							{description = "是,困难世界", data = "hard", hover = " "},
							{description = "是,非常困难的世界", data = "very hard", hover = " "},
						},
			default = false,
		},
		{
			name = "variate_islands",
			label = "岛屿数量",
			hover = "如果启用了“改变世界”，则平均应生成多少个岛（数量越多,岛屿越小）",
			options =	{
							{description = "默认", data = false, hover = "原岛屿数量"},
							{description = "随机", data = "random", hover = "随机岛屿数量"},
							{description = "很少", data = "few", hover = "任务数量的10-30%"},
							{description = "中等", data = "medium", hover = "任务数量的30-55%"},
							{description = "许多", data = "many", hover = "任务数量的50-80%"},
							{description = "全部", data = "all", hover = "尝试将每项任务都放到一个岛上（多个小岛）"},
						},
			default = false,
		},
		{
			name = "island_size_setting",
			label = "岛屿大小",
			hover = "如果启用了“改变世界”，岛屿应该有多大？（影响每个岛的任务数。不会改变普通的岛屿）",
			options =	{
							{description = "主小 其余相同", data = "mainsmall_othersamesize", hover = "主岛较小（2项任务），其余任务分配给其他岛屿。"},
							{description = "全部相同大小", data = "allsamesize", hover = "所有岛屿的大小大致相同（默认）"},
							{description = "主大 其余小", data = "mainbig_othersmall", hover = "岛屿将作为单个任务，其余任务将添加到主岛。"},
						},
			default = "allsamesize",
		},
		{
			name = "variate_suck",
			label = "改变骚扰？",
			hover = "如果启用了“改变世界”，还会随机设置：野火、疾病、青蛙雨、独眼巨鹿、蚁狮和石化",
			options =	{
							{description = "否", data = false, hover = "将使用您设置的世界设置。"},
							{description = "是", data = true, hover = " "},
						},
			default = true,
		},
		{
			name = "variate_specialevent",
			label = "改变事件？",
			hover = "如果启用了“改变世界”，则在此处设置下一个世界将发生一个随机特殊事件的机会",
			options =	{
							{description = "关闭", data = 0, hover = "将使用您设置的世界设置"},
							{description = "5%", data = 5, hover = " "},
							{description = "10%", data = 10, hover = " "},
							{description = "15%", data = 15, hover = " "},
							{description = "20%", data = 20, hover = " "},
							{description = "25%", data = 25, hover = " "},
							{description = "30%", data = 30, hover = " "},
							{description = "35%", data = 35, hover = " "},
							{description = "40%", data = 40, hover = " "},
							{description = "45%", data = 45, hover = " "},
							{description = "50%", data = 50, hover = " "},
							{description = "55%", data = 55, hover = " "},
							{description = "60%", data = 60, hover = " "},
							{description = "65%", data = 65, hover = " "},
							{description = "70%", data = 70, hover = " "},
							{description = "75%", data = 75, hover = " "},
							{description = "80%", data = 80, hover = " "},
							{description = "85%", data = 85, hover = " "},
							{description = "90%", data = 90, hover = " "},
							{description = "95%", data = 95, hover = " "},
							{description = "100%", data = 100, hover = " "},
						},
			default = 0,
		},
		{
			name = "DSlike",
			label = "类似于单机版",
				hover = "如果启用，您可以关闭我的所有更改，如更多的敌人、铥矿雕像和圆环周围的方尖碑",
			options =	{
							{description = "关闭", data = false, hover = " "},
							{description = "启用", data = true, hover = " "},
						},
			default = false,
		},
		{
			name = "newworld",
			label = "生成新世界",
				hover = "创造一个新的世界，旧的世界将被摧毁。您可以选择其他角色。在下面设置应转移的对象。\n管理员也可以在游戏过程中更改TUNING.TELEPORTATOMOD.TELENEWWORLD 的值来开/关此设置",
			options =	{
							{description = "关闭", data = false, hover = " "},
							{description = "启用", data = true, hover = " "},
						},
			default = true,
		},
		{
			name = "min_players",
			label = "最小玩家数",
			hover = "激活世界折跃所需的玩家数量",
			options =	{
							{description = "所有人数的一半", data = "half", hover = "默认。超过一半的在线玩家"},
							{description = "全部", data = "all", hover = "所有当前在线的玩家"},
							{description = "1", data = 1, hover = "1个在线玩家"},
							{description = "2", data = 2, hover = "2个在线玩家"},
							{description = "3", data = 3, hover = "3个在线玩家"},
							{description = "4", data = 4, hover = "4个在线玩家"},
							{description = "5", data = 5, hover = "5个在线玩家"},
							{description = "6", data = 6, hover = "6个在线玩家"},
							{description = "7", data = 7, hover = "7个在线玩家"},
							{description = "8", data = 8, hover = "8个在线玩家"},
							{description = "9", data = 9, hover = "9个在线玩家"},
							{description = "10", data = 10, hover = "10个在线玩家"},
							{description = "11", data = 11, hover = "11个在线玩家"},
							{description = "12", data = 12, hover = "12个在线玩家"},
							{description = "13", data = 13, hover = "13个在线玩家"},
							{description = "14", data = 14, hover = "14个在线玩家"},
							{description = "15", data = 15, hover = "15个在线玩家"},
							{description = "16", data = 16, hover = "16个在线玩家"},
						},
			default = "half",
		},
		{
			name = "agesave",
			label = "保存存活天数？",
				hover = "转移“存活天数”？如果启用，它会使下一个世界变得更困难，因为例如猎犬袭击会根据这个数字进行判断",
			options =	{
							{description = "否", data = false, hover = " "},
							{description = "是", data = true, hover = " "},
						},
			default = true,
		},
		{
			name = "inventorysave",
			label = "保存物品栏？",
				hover = "转移身上的物品？",
			options =	{
							{description = "否", data = false, hover = " "},
							{description = "是", data = true, hover = " "},
						},
			default = true,
		},
		{
			name = "inventorysavenumber",
			label = "保留物品数量？",
				hover = "应转移多少物品",
			options =	{
							{description = "所有", data = "all", hover = "所有物品和所有装备"},
							{description = "1", data = 1, hover = "只有前x项，不包括装备"},
							{description = "2", data = 2, hover = "只有前x项，不包括装备"},
							{description = "3", data = 3, hover = "只有前x项，不包括装备"},
							{description = "4", data = 4, hover = "只有前x项，不包括装备"},
							{description = "5", data = 5, hover = "只有前x项，不包括装备"},
							{description = "6", data = 6, hover = "只有前x项，不包括装备"},
							{description = "7", data = 7, hover = "只有前x项，不包括装备"},
							{description = "8", data = 8, hover = "只有前x项，不包括装备"},
						},
			default = "all",
		},
		{
			name = "recipesave",
			label = "保存原型？",
				hover = "转移原型和解锁配方？",
			options =	{
							{description = "否", data = false, hover = " "},
							{description = "是", data = true, hover = " "},
						},
			default = true,
		},
		{
			name = "statssave",
			label = "保存三维信息",
				hover = "转移当前的健康/理智/饥饿值？（但最低百分比为0.2、0.3和0.4）。例如 健康值不会低于20%。",
			options =	{
							{description = "否", data = false, hover = " "},
							{description = "是", data = true, hover = " "},
						},
			default = false,
		},
		{
			name = "ALLsave",
			label = "保存所有其他内容？",
				hover = "传输在您的角色上找到的所有其他尚未提及的数据。如果这导致问题或崩溃，请禁用此设置。",
			options =	{
							{description = "否", data = false, hover = "只能传输前面模组设置中提到的数据。"},
							{description = "是", data = true, hover = "只有在下一个世界中选择相同的角色时才有效。"},
						},
			default = true,
		},
		{
			name = "adv_itemcarrysandbox",
			label = "冒险模式的初始物品",
			hover = "当启用冒险模式时，能把你的东西从麦斯威尔之门带到冒险模式吗？",
			options = 
			{
				{description = "不，什么都没有", data = false, hover="你身上的任何东西都不会带入冒险模式"},
				{description = "是的，什么都有", data = true, hover="你的一切物品都将带入冒险模式"},
			},                   
			default = false,
		},
		{
			name = "announcepickparts",
			label = "宣布？",
				hover = "当有人捡起了一个传送基座部件时，会进行全服公告吗？",
			options =	{
							{description = "否", data = false, hover = " "},
							{description = "是", data = true, hover = " "},
						},
			default = false,
		},
		{
			name = "",
			label = "",
			hover = "",
			options =	{
							{description = "", data = 0},
						},
			default = 0,
		},
		{
			name = "Enemies",
			label = "守卫",
				hover = "应该有多少敌人守卫传送阵地？它们将在世界之初生成，并在激活传送基座后再次生成。",
			options =	{
							{description = "关闭", data = 0, hover = " "},
							{description = "很少", data = 0.5, hover = " "},
							{description = "中等", data = 1, hover = "默认"},
							{description = "许多", data = 2, hover = " "},
						},
			default = 1,
		},
		{
			name = "RegeneratePlayerHealth",
			label = "玩家生命恢复",
				hover = "所有在传送基座附近的玩家都会慢慢恢复生命值",
			options =	{
							{description = "关闭", data = 0, hover = " "},
							{description = "-1", data = -1, hover = "每5秒"},
							{description = "-0.5", data = -0.5, hover = "每5秒"},
							{description = "-0.25", data = -0.25, hover = "每5秒"},
							{description = "0.25", data = 0.25, hover = "每5秒"},
							{description = "0.5", data = 0.5, hover = "每5秒"},
							{description = "1", data = 1, hover = "每5秒"},
							{description = "2", data = 2, hover = "每5秒 (默认)"},
							{description = "3", data = 3, hover = "每5秒"},
							{description = "4", data = 4, hover = "每5秒"},
							{description = "5", data = 5, hover = "每5秒"},
						},
			default = 2,
		},
		{
			name = "RegeneratePlayerHunger",
			label = "玩家饥饿值再生",
				hover = "所有在传送基座附近的玩家都会慢慢恢复饥饿值",
			options =	{
							{description = "关闭", data = 0, hover = " "},
							{description = "-1", data = -1, hover = "每5秒"},
							{description = "-0.5", data = -0.5, hover = "每5秒"},
							{description = "-0.25", data = -0.25, hover = "每5秒"},
							{description = "0.25", data = 0.25, hover = "每5秒 (默认)"},
							{description = "0.5", data = 0.5, hover = "每5秒"},
							{description = "1", data = 1, hover = "每5秒"},
							{description = "2", data = 2, hover = "每5秒"},
							{description = "3", data = 3, hover = "每5秒"},
							{description = "4", data = 4, hover = "每5秒"},
							{description = "5", data = 5, hover = "每5秒"},
						},
			default = 0.25,
		},
		{
			name = "RegeneratePlayerSanity",
			label = "玩家精神值再生",
				hover = "所有在传送基座附近的玩家都会慢慢恢复精神值",
			options =	{
							{description = "关闭", data = 0, hover = " "},
							{description = "正常下降", data = 1, hover = " "},
							{description = "缓慢下降", data = 2, hover = " "},
							{description = "极慢下降", data = 3, hover = " "},
							{description = "极慢上升", data = 4, hover = " "},
							{description = "缓慢上升", data = 5, hover = " "},
							{description = "较慢上升", data = 6, hover = "默认"},
							{description = "正常上升", data = 7, hover = " "},
							{description = "快速上升", data = 8, hover = " "},
							{description = "极快上升", data = 9, hover = " "},
						},
			default = 6,
		},
		{
			name = "Ancient",
			label = "远古科学站",
				hover = "产生一个远古伪科学站。还有一个敌人。",
			options =	{
							{description = "关闭", data = 0, hover = " "},
							{description = "残缺", data = 1, hover = "铥矿将在你发现传送基座部件的地方生成！但也有一些敌人。（默认）"}, -- "thulecite_pieces" "thulecite" "pandoraschest"
							{description = "完整的", data = 2, hover = " "}, -- "ruins_statue_mage" "ruins_statue_mage_nogem"
						},
			default = 1,
		},
		{
			name = "Thulecite",
			label = "铥矿",
				hover = "完成传送基座时在基座附近与基座部件之前的位置生成铥矿",
			options =	{
							{description = "关闭", data = 0, hover = " "},
							{description = "很少", data = 1, hover = " "},
							{description = "中等", data = 2, hover = "默认"},
							{description = "许多", data = 3, hover = " "},
						},
			default = 2,
		},
		{
			name = "Chests",
			label = "宝箱",
			hover = "完成传送基座时在基座附近与基座部件之前的位置生成宝箱。但也有一些敌人。",
			options =	{
							{description = "关闭", data = 0, hover = " "},
							{description = "很少", data = 1, hover = " "},
							{description = "中等", data = 2, hover = "默认"},
							{description = "许多", data = 3, hover = " "},
						},
			default = 2,
		},
		{
			name = "",
			label = "",
			hover = "",
			options =	{
							{description = "", data = 0},
						},
			default = 0,
		},
		{
			name = "set_behaviour",
			label = "放置方式",
			hover = "通常只有在没有其他物体阻挡位置时才会放置零件。因此可能会出现其中一个不存在的情况。",
			options =   {
							{description = "忽略贫瘠", data = 1, hover = "放置时忽略不可通行和贫瘠。"},
							{description = "全部忽略", data = 2, hover = "还会忽略其他设置物件，但可能会与其他物品出现在同一位置。"},
							{description = "忽略贫瘠+要求", data = 4, hover = "与忽略贫瘠相同，但世界将重新生成，直到所有零件都放置完成。"},
							{description = "全部忽略+要求", data = 5, hover = "与忽略贫瘠+要求相同，但还包括全部忽略。"}, -- usually IgnoreAll will be 100% gurantee, but not if modworldgenmain spawns them as story setpieces, which is only true for adventure mode
						},
			default = 4,
		},
		{
			name = "spawnteleworld",
			label = "哪个世界",
			hover = "零件应该在森林还是洞穴或两者都生成？基座始终在森林中。零件可以在世界之间转移。",
			options =   {
							{description = "森林", data = "forest", hover = "默认"},
							{description = "洞穴", data = "cave", hover = "只有零件。基座总是在森林里"},
							{description = "二者都有", data = "forestcave", hover = "两个世界都有一整套零件，而基座只在森林中"},
						},
			default = "forest",
		},
		{
			name = "spawntelemoonisland",
			label = "月岛？",
			hover = "基座/部件是否也应该在月岛生成？",
			options =   {
							{description = "否", data = false, hover = ""},
							{description = "是", data = true, hover = "也适用于其他级别的岛（目前只有月岛）	"},
						},
			default = true,
		},
	}
}
return info