local function Breaker(name, label, hover, options, default)
	return { name = name, label = label, hover = hover or "", options = options, default = default }
end

local function Title(title,label)
	return Breaker(title, label, "", { { description = "", data = 0 } }, 0)
end

--
local options_health = {
	{ description = "10",  data = 10 },
	{ description = "25",  data = 25 },
	{ description = "50",  data = 50 },
	{ description = "75",  data = 75 },
	{ description = "100", data = 100 },
	{ description = "120", data = 120 },
	{ description = "125", data = 125 },
	{ description = "130", data = 130 },
	{ description = "140", data = 140 },
	{ description = "150", data = 150 },
	{ description = "175", data = 175 },
	{ description = "200", data = 200 },
	{ description = "250", data = 250 },
	{ description = "260", data = 260 },
	{ description = "270", data = 270 },
	{ description = "300", data = 300 },
	{ description = "375", data = 375 },
	{ description = "400", data = 400 },
	{ description = "500", data = 500 },
}
--
local options_hunger = {
	{ description = "10",  data = 10 },
	{ description = "25",  data = 25 },
	{ description = "50",  data = 50 },
	{ description = "75",  data = 75 },
	{ description = "100", data = 100 },
	{ description = "110", data = 110 },
	{ description = "120", data = 120 },
	{ description = "125", data = 125 },
	{ description = "130", data = 130 },
	{ description = "140", data = 140 },
	{ description = "150", data = 150 },
	{ description = "170", data = 170 },
	{ description = "200", data = 200 },
	{ description = "230", data = 230 },
	{ description = "250", data = 250 },
	{ description = "270", data = 270 },
	{ description = "300", data = 300 },
	{ description = "375", data = 375 },
	{ description = "400", data = 400 },
	{ description = "500", data = 500 },
}
--
local options_sanity = {
	{ description = "10",  data = 10 },
	{ description = "25",  data = 25 },
	{ description = "50",  data = 50 },
	{ description = "75",  data = 75 },
	{ description = "100", data = 100 },
	{ description = "120", data = 120 },
	{ description = "125", data = 125 },
	{ description = "130", data = 130 },
	{ description = "140", data = 140 },
	{ description = "150", data = 150 },
	{ description = "175", data = 175 },
	{ description = "200", data = 200 },
	{ description = "250", data = 250 },
	{ description = "275", data = 275 },
	{ description = "300", data = 300 },
	{ description = "375", data = 375 },
	{ description = "400", data = 400 },
	{ description = "500", data = 500 },
}
local options_hundred = {
	{data=0,description="0"}, {data=1,description="1"}, {data=2,description="2"}, {data=3,description="3"}, {data=4,description="4"}, {data=5,description="5"},
	{data=6,description="6"}, {data=7,description="7"}, {data=8,description="8"}, {data=9,description="9"}, {data=10,description="10"},
	{data=11,description="11"}, {data=12,description="12"}, {data=13,description="13"}, {data=14,description="14"}, {data=15,description="15"},
	{data=16,description="16"}, {data=17,description="17"}, {data=18,description="18"}, {data=19,description="19"}, {data=20,description="20"},
	{data=21,description="21"}, {data=22,description="22"}, {data=23,description="23"}, {data=24,description="24"}, {data=25,description="25"},
	{data=26,description="26"}, {data=27,description="27"}, {data=28,description="28"}, {data=29,description="29"}, {data=30,description="30"},
	{data=31,description="31"}, {data=32,description="32"}, {data=33,description="33"}, {data=34,description="34"}, {data=35,description="35"},
	{data=36,description="36"}, {data=37,description="37"}, {data=38,description="38"}, {data=39,description="39"}, {data=40,description="40"},
	{data=41,description="41"}, {data=42,description="42"}, {data=43,description="43"}, {data=44,description="44"}, {data=45,description="45"},
	{data=46,description="46"}, {data=47,description="47"}, {data=48,description="48"}, {data=49,description="49"}, {data=50,description="50"},
	{data=51,description="51"}, {data=52,description="52"}, {data=53,description="53"}, {data=54,description="54"}, {data=55,description="55"},
	{data=56,description="56"}, {data=57,description="57"}, {data=58,description="58"}, {data=59,description="59"}, {data=60,description="60"},
	{data=61,description="61"}, {data=62,description="62"}, {data=63,description="63"}, {data=64,description="64"}, {data=65,description="65"},
	{data=66,description="66"}, {data=67,description="67"}, {data=68,description="68"}, {data=69,description="69"}, {data=70,description="70"},
	{data=71,description="71"}, {data=72,description="72"}, {data=73,description="73"}, {data=74,description="74"}, {data=75,description="75"},
	{data=76,description="76"}, {data=77,description="77"}, {data=78,description="78"}, {data=79,description="79"}, {data=80,description="80"},
	{data=81,description="81"}, {data=82,description="82"}, {data=83,description="83"}, {data=84,description="84"}, {data=85,description="85"},
	{data=86,description="86"}, {data=87,description="87"}, {data=88,description="88"}, {data=89,description="89"}, {data=90,description="90"},
	{data=91,description="91"}, {data=92,description="92"}, {data=93,description="93"}, {data=94,description="94"}, {data=95,description="95"},
	{data=96,description="96"}, {data=97,description="97"}, {data=98,description="98"}, {data=99,description="99"}, {data=100,description="100"},
}
--
local description = KnownModIndex:GetModInfo("workshop-2010472942").description
description = string.gsub(description,"The 4 iconic Don't Starve: Reign of Giants bosses reimagined.","《饥荒：巨人国》的4个标志性BOSS重新构想。")
description = string.gsub(description,"They're looking a little smaller than usual...%?","它们看起来比平时小了点...？")
description = string.gsub(description,"Skill Tree Spotlight","技能树聚点")
description = string.gsub(description,"Dragonfly","龙蝇")
--
local info={
	name = "Reign of Runts(侏儒的统治)",
	description = description,
	configuration_options =
	{
		--BEARGER
		Title("Bearger","小熊獾"),
		{
			name    = "enable_wearger",
			label   = "启用熊獾",
			hover   = "启用或禁用熊獾",
			options =
			{
				{ description = "是", data = true },
				{ description = "否", data = false },
			},
			default = true,
		},
		{
			name    = "wearger_health",
			label   = "熊獾的生命值",
			options = options_health,
			default = 175,
		},
		{
			name    = "wearger_hunger",
			label   = "熊獾的饥饿值",
			options = options_hunger,
			default = 230,
		},
		{
			name    = "wearger_sanity",
			label   = "熊獾的精神值",
			options = options_sanity,
			default = 150,
		},
		{
			name    = "enable_wearger_skills",
			label   = "启用技能树",
			hover   = "启用或禁用熊獾的技能树。",
			options =
			{
				{ description = "开启", data = true },
				{ description = "关闭", data = false },
			},
			default = true,
		},
		{
			name    = "wearger_attackstyle",
			label   = "熊獾拍地攻击",
			hover   = "让熊獾的重击成为一个额外的鼠标右键动作或原来的每四次攻击风格。",
			options =
			{
				{ description = "每4次", data = 1 },
				{ description = "鼠标右键执行动作", data = 2 },
				{ description = "都不包括", data = 3 },
				{ description = "都包括", data = 4 },
			},
			default = 2,
		},
		{
			name    = "wearg_gpdmg_v2",
			label   = "熊獾拍地伤害",
			hover	= "熊獾的拍地攻击造成的AoE伤害\n近距离伤害值相同。",
			options = options_hundred,
			default = 25,
		},
		{
			name    = "enable_groundpcancel",
			label   = "拍地动画取消",
			hover	= "允许您取消熊獾的地面猛击动画，就像其他攻击动画一样。",
			options =
			{
				{description = "是", data = true,
				hover = "仅适用于“每4次”配置选项"},
				{description = "否", data = false},
			},
			default = true,
		},
		{
			name    = "wearger_gp_cd",
			label   = "拍地攻击冷却时间",
			hover   = "在熊獾地面猛击之间等待的时间，以秒为单位。",
			options =
			{
				{ description = "0 秒",   data = 0 },
				{ description = "1 秒",   data = 1 },
				{ description = "2 秒",   data = 2 },
				{ description = "3 秒",   data = 3 },
				{ description = "4 秒",   data = 4 },
				{ description = "5 秒",   data = 5 },
				{ description = "10 秒",  data = 10 },
				{ description = "15 秒",  data = 15 },
				{ description = "20 秒",  data = 20 },
				{ description = "25 秒",  data = 25 },
				{ description = "30 秒",  data = 30 },
				{ description = "35 秒",  data = 35 },
				{ description = "40 秒",  data = 40 },
				{ description = "45 秒",  data = 45 },
				{ description = "50 秒",  data = 50 },
				{ description = "1 分",   data = 60 },
				{ description = "1.5 分", data = 90 },
				{ description = "2 分",   data = 120 },
				{ description = "3 分",   data = 150 },
				{ description = "4 分",   data = 240 },
				{ description = "5 分",   data = 300 },
				{ description = "10 分",  data = 1600 },
			},
			default = 3,
		},
		{
			name    = "wearger_gp_range_v2",
			label   = "拍地攻击范围",
			hover	= "地面猛击可以影响多少距离。",
			options = options_hundred,
			default = 5,
		},
		{
			name    = "wearger_gp_pick",
			label   = "地面猛击可采集物品",
			hover   = "地面猛击是否会采集附近的可采集物品：浆果丛、树苗、草等。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = true,
		},
		{
			name    = "wearg_hungerd",
			label   = "熊獾饥饿值消耗",
			hover   = "熊獾的饥饿值消耗速度增加了多少。",
			options =
			{
				{ description = "0%",   data = 0 },
				{ description = "5%",   data = 1.05 },
				{ description = "10%",  data = 1.10 },
				{ description = "15%",  data = 1.15 },
				{ description = "20%",  data = 1.20 },
				{ description = "25%",  data = 1.25 },
				{ description = "30%",  data = 1.30 },
				{ description = "35%",  data = 1.35 },
				{ description = "40%",  data = 1.40 },
				{ description = "45%",  data = 1.45 },
				{ description = "50%",  data = 1.50 },
				{ description = "60%",  data = 1.60 },
				{ description = "70%",  data = 1.70 },
				{ description = "80%",  data = 1.80 },
				{ description = "90%",  data = 1.90 },
				{ description = "100%", data = 1.100 },
			},
			default = 1.20,
		},
		{
			name    = "wearg_honey",
			label   = "熊獾蜜糖奖励",
			hover   = "熊獾食用蜜糖食物时获得的额外精神值加成。",
			options = options_hundred,
			default = 10,
		},
		{
			name    = "wearger_beeresist",
			label   = "蜜蜂抵抗力",
			hover	= "蜜蜂对熊獾造成的伤害减少了多少百分比",
			options =
			{
				{description = "0%", data = 0},
				{description = "5%", data = 0.05},
				{description = "10%", data = 0.10},
				{description = "15%", data = 0.15},
				{description = "20%", data = 0.20},
				{description = "25%", data = 0.25},
				{description = "30%", data = 0.30},
				{description = "35%", data = 0.35},
				{description = "40%", data = 0.40},
				{description = "45%", data = 0.45},
				{description = "50%", data = 0.5},
				{description = "60%", data = 0.6},
				{description = "70%", data = 0.7},
				{description = "80%", data = 0.8},
				{description = "90%", data = 0.9},
				{description = "100%", data = 1},
			},
			default = 0.5,
		},
		{
			name    = "wearger_hibasorp",
			label   = "冬眠吸收伤害",
			hover   = "熊獾在冬眠状态下受到的伤害减少了多少百分比。",
			options =
			{
				{ description = "0%",   data = 0 },
				{ description = "5%",   data = 0.05 },
				{ description = "10%",  data = 0.10 },
				{ description = "15%",  data = 0.15 },
				{ description = "20%",  data = 0.20 },
				{ description = "25%",  data = 0.25 },
				{ description = "30%",  data = 0.30 },
				{ description = "35%",  data = 0.35 },
				{ description = "40%",  data = 0.40 },
				{ description = "45%",  data = 0.45 },
				{ description = "50%",  data = 0.5 },
				{ description = "60%",  data = 0.6 },
				{ description = "70%",  data = 0.7 },
				{ description = "80%",  data = 0.8 },
				{ description = "90%",  data = 0.9 },
				{ description = "100%", data = 1 },
			},
			default = 0.20,
		},
		{
			name    = "wearger_yawn",
			label   = "熊獾打哈欠几率",
			hover   = "在冬眠状态下，熊獾打哈欠替代地磅攻击的几率百分比。",
			options =
			{
				{ description = "0%",   data = 0 },
				{ description = "5%",   data = .05 },
				{ description = "10%",  data = .1 },
				{ description = "15%",  data = .15 },
				{ description = "20%",  data = .2 },
				{ description = "25%",  data = .25 },
				{ description = "30%",  data = .3 },
				{ description = "35%",  data = .35 },
				{ description = "40%",  data = .4 },
				{ description = "45%",  data = .45 },
				{ description = "50%",  data = .5 },
				{ description = "60%",  data = .6 },
				{ description = "70%",  data = .7 },
				{ description = "80%",  data = .8 },
				{ description = "90%",  data = .9 },
				{ description = "100%", data = 1 },
			},
			default = .2,
		},
		--DEERCLOPS
		Title("Deerclops","小鹿"),
		{
			name    = "enable_weerclops",
			label   = "启用巨鹿",
			hover   = "启用或禁用巨鹿",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = true,
		},
		{
			name    = "weerclops_health",
			label   = "巨鹿的生命值",
			options = options_health,
			default = 150,
		},
		{
			name    = "weerclops_hunger",
			label   = "巨鹿的饥饿值",
			options = options_hunger,
			default = 150,
		},
		{
			name    = "weerclops_sanity",
			label   = "巨鹿的理智值",
			options = options_sanity,
			default = 120,
		},
		{
			name    = "weerclops_attackstyle",
			label   = "巨鹿的冰攻击",
			hover   = "巨鹿的攻击是否能够冻结敌人。",
			options =
			{
				{ description = "否",  data = 0 },
				{ description = "是", data = 1 },
			},
			default = 1,
		},
		{
			name    = "weerclops_fx",
			label   = "巨鹿的冰效果",
			hover   = "在攻击和破坏时，是否启用巨鹿的视觉/音频冰效果。",
			options =
			{
				{ description = "禁用", data = 0 },
				{ description = "启用", data = 1 },
			},
			default = 1,
		},
		{
			name    = "weerclops_ice_range",
			label   = "巨鹿的冬季范围攻击距离",
			hover   = "巨鹿的冷气攻击在冬季中影响的距离。",
			options =
			{
				{ description = "0",  data = 0 },
				{ description = "1",  data = 1 },
				{ description = "2",  data = 2 },
				{ description = "3",  data = 3 },
				{ description = "4",  data = 4 },
				{ description = "5",  data = 5 },
				{ description = "6",  data = 6 },
				{ description = "7",  data = 7 },
				{ description = "8",  data = 8 },
				{ description = "9",  data = 9 },
				{ description = "10", data = 10 },
				{ description = "15", data = 15 },
				{ description = "20", data = 20 },
				{ description = "25", data = 25 },
				{ description = "30", data = 30 },
			},
			default = 4,
		},
		{
			name    = "weer_sanitydrainstart",
			label   = "巨鹿理智耗竭开始时间",
			hover   = "从第一阶段开始无需破坏的理智耗竭需要多长时间（以天为单位）。",
			options =
			{
				{ description = "立即", data = 0 },
				{ description = ".5 天", data = .5 },
				{ description = "1 天", data = 1 },
				{ description = "1.5 天", data = 1.5 },
				{ description = "2 天", data = 2 },
				{ description = "2.5 天", data = 2.5 },
				{ description = "3 天", data = 3 },
				{ description = "3.5 天", data = 3.5 },
				{ description = "4 天", data = 4 },
				{ description = "5 天", data = 5 },
				{ description = "6 天", data = 6 },
				{ description = "7 天", data = 7 },
				{ description = "10 天", data = 10 },
				{ description = "从不", data = 100000 }, --Cheat
			},
			default = 2,
		},
		{
			name    = "weer_sanitybonus",
			label   = "巨鹿摧毁建筑物理智增加",
			hover   = "巨鹿摧毁一座建筑物所获得的理智值。（可调整比例）",
			options = options_hundred,
			default = 5,
		},
		{
			name    = "weer_freezekill",
			label   = "巨鹿冻结致死时间",
			hover   = "冻结需要的时间相对缓慢，以致于杀死巨鹿所需的时间延长了多少%。",
			options =
			{
				{ description = "0%",    data = 120 },
				{ description = "-10%",  data = 132 },
				{ description = "-20%",  data = 144 },
				{ description = "-30%",  data = 156 },
				{ description = "-40%",  data = 168 },
				{ description = "-50%",  data = 180 },
				{ description = "-60%",  data = 192 },
				{ description = "-70%",  data = 204 },
				{ description = "-80%",  data = 216 },
				{ description = "-90%",  data = 228 },
				{ description = "-100%", data = 240 },
			},
			default = 216,
		},
		{
			name    = "weer_hotkill",
			label   = "过热杀死巨鹿时间",
			hover   = "巨鹿因过热而死亡所需时间缩短了多少%。",
			options =
			{
				{ description = "0%",  data = 120 },
				{ description = "10%", data = 108 },
				{ description = "20%", data = 96 },
				{ description = "30%", data = 84 },
				{ description = "40%", data = 72 },
				{ description = "50%", data = 60 },
				{ description = "60%", data = 48 },
				{ description = "70%", data = 36 },
			},
			default = 84,
		},
		--DRAGONFLY
		Title("Dragonfly","小龙蝇"),
		{
			name    = "enable_wragonfly",
			label   = "启用龙蝇",
			hover   = "启用或禁用龙蝇",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = true,
		},
		{
			name    = "wragonfly_health",
			label   = "龙蝇的生命值",
			options = options_health,
			default = 200,
		},
		{
			name    = "wragonfly_hunger",
			label   = "龙蝇的饥饿值",
			options = options_hunger,
			default = 175,
		},
		{
			name    = "wragonfly_sanity",
			label   = "龙蝇的理智值",
			options = options_sanity,
			default = 100,
		},
		{
			name    = "enable_wragonfly_skills",
			label   = "启用技能树",
			hover	= "启用或禁用龙蝇的技能树。",
			options =
			{
				{description = "启用", data = true},
				{description = "禁用", data = false},
			},
			default = true,
		},
		{
			name    = "wfly_fireimmune",
			label   = "龙蝇火焰免疫",
			hover   = "即使未进入暴怒状态，龙蝇依然具有对火焰免疫的能力.",
			options =
			{
				{ description = "是", data = 0 },
				{ description = "否",  data = 1 },
			},
			default = 0,
		},
		{
			name    = "wfly_enraged_timer",
			label   = "暴怒时间",
			hover   = "龙蝇在她暴怒状态下停留的时间。以秒为单位。",
			options =
			{
				{ description = "0 秒", data = 0 },
				{ description = "5 秒",     data = 5 },
				{ description = "10 秒",    data = 10 },
				{ description = "15 秒",    data = 15 },
				{ description = "20 秒",    data = 20 },
				{ description = "25 秒",    data = 25 },
				{ description = "30 秒",    data = 30 },
				{ description = "35 秒",    data = 35 },
				{ description = "40 秒",    data = 40 },
				{ description = "45 秒",    data = 45 },
				{ description = "50 秒",    data = 50 },
				{ description = "1 分",     data = 60 },
				{ description = "1.5 分",   data = 90 },
				{ description = "2 分",     data = 120 },
				{ description = "3 分",     data = 150 },
				{ description = "4 分",     data = 240 },
				{ description = "5 分",     data = 300 },
				{ description = "10 分",    data = 1600 },
			},
			default = 60,
		},
		{
			name    = "wfly_enraged_cd",
			label   = "暴怒冷却时间",
			hover   = "龙蝇再次进入暴怒状态之前的时间间隔。以秒为单位。",
			options =
			{
				{ description = "0 秒", data = 0 },
				{ description = "5 秒",     data = 5 },
				{ description = "10 秒",    data = 10 },
				{ description = "15 秒",    data = 15 },
				{ description = "20 秒",    data = 20 },
				{ description = "25 秒",    data = 25 },
				{ description = "30 秒",    data = 30 },
				{ description = "35 秒",    data = 35 },
				{ description = "40 秒",    data = 40 },
				{ description = "45 秒",    data = 45 },
				{ description = "50 秒",    data = 50 },
				{ description = "1 分",     data = 60 },
				{ description = "1.5 分",   data = 90 },
				{ description = "2 分",     data = 120 },
				{ description = "3 分",     data = 150 },
				{ description = "4 分",     data = 240 },
				{ description = "5 分",     data = 300 },
				{ description = "10 分",    data = 1600 },
			},
			default = 30,
		},
		{
			name    = "wfly_enraged_fire",
			label   = "愤怒的火焰攻击",
			hover   = "当愤怒时，使龙蝇造成火焰伤害，类似于用火把战斗。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = false,
		},
		{
			name    = "wfly_summondmg",
			label   = "熔岩虫召唤惩罚",
			hover   = "召唤熔岩虫需要消耗多少生命和饥饿值。如果使用灰烬，则减半。",
			options = options_hundred,
			default = 20,
		},
		{
			name    = "wfly_enraged_maxhp",
			label   = "额外的愤怒生命值",
			hover   = "愤怒状态下获得的额外最大生命值。",
			options = options_hundred,
			default = 70,
		},
		{
			name    = "wfly_atk_mult",
			label   = "额外的愤怒伤害",
			hover   = "愤怒状态下龙蝇造成的额外伤害比例。",
			options =
			{
				{ description = "0%",   data = 1 },
				{ description = "5%",   data = 1.05 },
				{ description = "10%",  data = 1.1 },
				{ description = "15%",  data = 1.15 },
				{ description = "20%",  data = 1.2 },
				{ description = "30%",  data = 1.3 },
				{ description = "40%",  data = 1.4 },
				{ description = "50%",  data = 1.5 },
				{ description = "60%",  data = 1.6 },
				{ description = "70%",  data = 1.7 },
				{ description = "80%",  data = 1.8 },
				{ description = "90%",  data = 1.9 },
				{ description = "100%", data = 2 },
			},
			default = 1.1,
		},
		{
			name    = "wfly_enraged_burstdmg",
			label   = "愤怒爆发伤害",
			hover   = "愤怒状态下龙蝇额外的火焰爆发造成的伤害。可以乘以2.5或者5倍。",
			options = options_hundred,
			default = 10,
		},
		{
			name    = "wfly_spd_mult",
			label   = "额外的愤怒速度",
			hover   = "愤怒状态下龙蝇获得的额外速度增加比例。",
			options =
			{
				{ description = "0%",   data = 1 },
				{ description = "5%",   data = 1.05 },
				{ description = "10%",  data = 1.1 },
				{ description = "15%",  data = 1.15 },
				{ description = "20%",  data = 1.2 },
				{ description = "30%",  data = 1.3 },
				{ description = "40%",  data = 1.4 },
				{ description = "50%",  data = 1.5 },
				{ description = "60%",  data = 1.6 },
				{ description = "70%",  data = 1.7 },
				{ description = "80%",  data = 1.8 },
				{ description = "90%",  data = 1.9 },
				{ description = "100%", data = 2 },
			},
			default = 1.2,
		},
		{
			name    = "wfly_ashes",
			label   = "灰烬进食量导致暴怒 #",
			hover   = "龙蝇需要吃多少灰烬才能变得暴怒。过度进食会导致昏昏欲睡 # + 2。",
			options =
			{
				{
					description = "0",
					data = 0,
					hover = "0 完全禁止吃灰激怒。但它们仍然会让她昏昏沉沉!"
				},
				{ description = "1",  data = 1 },
				{ description = "2",  data = 2 },
				{ description = "3",  data = 3 },
				{ description = "4",  data = 4 },
				{ description = "5",  data = 5 },
				{ description = "6",  data = 6 },
				{ description = "7",  data = 7 },
				{ description = "8",  data = 8 },
				{ description = "9",  data = 9 },
				{ description = "10", data = 10 },
				{ description = "11", data = 11 },
				{ description = "12", data = 12 },
				{ description = "13", data = 13 },
				{ description = "14", data = 14 },
				{ description = "15", data = 15 },
				{ description = "20", data = 20 },
				{ description = "25", data = 25 },
				{ description = "30", data = 30 },
				{ description = "35", data = 35 },
				{ description = "40", data = 40 },
				{ description = "45", data = 45 },
				{ description = "50", data = 50 },
				{ description = "60", data = 60 },
			},
			default = 8,
		},
		{
			name    = "wfly_oheattemp",
			label   = "龙蝇过热温度",
			hover   = "龙蝇将开始受到过热伤害的温度。威尔逊是70。",
			options =
			{
				{ description = "10", data = 10 },
				{ description = "20", data = 20 },
				{ description = "30", data = 30 },
				{ description = "40", data = 40 },
				{ description = "50", data = 50 },
				{ description = "60", data = 60 },
				{ description = "70", data = 70 },
				{ description = "80", data = 80 },
				{ description = "90", data = 90 },
				{ description = "99", data = 98 },
			},
			default = 90,
		},
		{
			name    = "wfly_lavaedmg",
			label   = "熔岩虫伤害",
			hover   = "龙蝇的熔岩虫每次攻击造成的伤害量。",
			options = options_hundred,
			default = 50,
		},
		{
			name    = "wfly_lavaehp",
			label   = "熔岩虫生命值",
			hover	= "熔岩虫的最大生命值。",
			options = options_health,
			default = 500,
		},
		{
			name    = "wfly_lavaemax",
			label   = "最大熔岩虫",
			hover   = "龙蝇同时可以拥有多少个熔岩虫。",
			options =
			{
				{ description = "1",  data = 0 }, --player_common inherently has it set to 1
				{ description = "2",  data = 1 },
				{ description = "3",  data = 2 },
				{ description = "4",  data = 3 },
				{ description = "5",  data = 4 },
				{ description = "6",  data = 5 },
				{ description = "7",  data = 6 },
				{ description = "8",  data = 7 },
				{ description = "9",  data = 8 },
				{ description = "10", data = 9 },
				{ description = "11", data = 10 },
				{ description = "12", data = 11 },
				{ description = "13", data = 12 },
				{ description = "14", data = 13 },
				{ description = "15", data = 14 },
				{ description = "16", data = 15 },
				{ description = "20", data = 19 },
				{ description = "25", data = 24 },
				{ description = "30", data = 29 },
				{ description = "35", data = 34 },
				{ description = "40", data = 39 },
				{ description = "45", data = 44 },
				{ description = "50", data = 49 },
				{ description = "60", data = 59 },
			},
			default = 9,
		},
		--MOOSE/GOOSE
		Title("Moose/Goose","小麋鹿鹅"),
		{
			name    = "enable_woose",
			label   = "启用麋鹿鹅",
			hover   = "启用或禁用麋鹿鹅。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = true,
		},

		{
			name    = "woose_health",
			label   = "麋鹿鹅的生命值",
			options = options_health,
			default = 175,
		},
		{
			name    = "woose_hunger",
			label   = "麋鹿鹅的饥饿值",
			options = options_hunger,
			default = 150,
		},
		{
			name    = "woose_sanity",
			label   = "麋鹿鹅的精神值",
			options = options_sanity,
			default = 200,
		},
		{
			name    = "enable_woose_speen",
			label   = "启用旋转",
			hover   = "启用或禁用鹅的旋转动作。",
			options =
			{
				{ description = "启用", data = true },
				{ description = "禁用", data = false },
			},
			default = true,
		},
		{
			name    = "woose_drownmax",
			label   = "麋鹿鹅湿度溺水阈值",
			hover   = "麋鹿鹅在海洋中可以承受多少湿度，直到她淹死。",
			options =
			{
				{
					description = "0",
					data = 0,
					hover = "0完全禁止在水上行走。"
				},
				{ description = "5",   data = 5 },
				{ description = "10",  data = 10 },
				{ description = "12",  data = 12 },
				{ description = "15",  data = 15 },
				{ description = "16",  data = 16 },
				{ description = "17",  data = 17 },
				{ description = "20",  data = 20 },
				{ description = "25",  data = 25 },
				{ description = "30",  data = 30 },
				{ description = "35",  data = 35 },
				{ description = "40",  data = 40 },
				{ description = "45",  data = 45 },
				{ description = "50",  data = 50 },
				{ description = "60",  data = 60 },
				{ description = "70",  data = 70 },
				{ description = "80",  data = 80 },
				{ description = "90",  data = 90 },
				{ description = "100", data = 100 },
				{
					description = "从不",
					data = 1000,
					hover = "不论你的湿度如何，你都不会淹死。"
				},
			},
			default = 80,
		},

		{
			name    = "woose_honkrange",
			label   = "鹅鸣范围",
			hover   = "喇叭声有多远.",
			options =
			{
				{ description = "0",  data = 0 },
				{ description = "1",  data = 1 },
				{ description = "2",  data = 2 },
				{ description = "3",  data = 3 },
				{ description = "4",  data = 4 },
				{ description = "5",  data = 5 },
				{ description = "6",  data = 6 },
				{ description = "7",  data = 7 },
				{ description = "8",  data = 8 },
				{ description = "9",  data = 9 },
				{ description = "10", data = 10 },
			},
			default = 5,
		},
		{
			name    = "woose_wetdrain",
			label   = "麋鹿鹅不受湿度精神减益",
			hover   = "使麋鹿鹅不因湿度过高而受到精神减益。不包括湿度工具的精神减益。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否", data = false },
			},
			default = false,
		},
		{
			name    = "woose_wetness",
			label   = "鹅湿度增加速度",
			hover   = "麋鹿鹅湿度增加的速度是原来的百分之多少。适用于雨水和任何会逐渐增加湿度的情况。包括在水上行走时的情况！",
			options =
			{
				{ description = "0%",   data = 1 },
				{ description = "5%",   data = 1.05 },
				{ description = "10%",  data = 1.1 },
				{ description = "20%",  data = 1.2 },
				{ description = "33%",  data = 1.33 },
				{ description = "40%",  data = 1.4 },
				{ description = "50%",  data = 1.5 },
				{ description = "60%",  data = 1.6 },
				{ description = "70%",  data = 1.7 },
				{ description = "80%",  data = 1.8 },
				{ description = "90%",  data = 1.9 },
				{ description = "100%", data = 2 },
			},
			default = 1.6,
		},
		{
			name    = "enable_nesting",
			label   = "启用巢穴",
			hover   = "允许麋鹿鹅制作可放置的巢穴，提供母性增益。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = true,
		},
		{
			name    = "woose_nestbuff",
			label   = "巢穴增益吸收",
			hover   = "一个活跃的巢穴散发出的伤害吸收百分比。不会叠加。",
			options =
			{
				{ description = "0%",   data = 0 },
				{ description = "5%",   data = 0.05 },
				{ description = "10%",  data = 0.10 },
				{ description = "15%",  data = 0.15 },
				{ description = "20%",  data = 0.20 },
				{ description = "25%",  data = 0.25 },
				{ description = "30%",  data = 0.30 },
				{ description = "35%",  data = 0.35 },
				{ description = "40%",  data = 0.40 },
				{ description = "45%",  data = 0.45 },
				{ description = "50%",  data = 0.5 },
				{ description = "60%",  data = 0.6 },
				{ description = "70%",  data = 0.7 },
				{ description = "80%",  data = 0.8 },
				{ description = "90%",  data = 0.9 },
				{ description = "100%", data = 1 },
			},
			default = 0.25,
		},
		{
			name    = "woose_nesttime",
			label   = "巢穴腐烂时间",
			hover   = "如果巢穴未被加料，自然腐烂所需的时间，以天为单位。",
			options =
			{
				{ description = "半天", data = .5 },
				{ description = "1 天", data = 1 },
				{ description = "1.5 天", data = 1.5 },
				{ description = "2 天", data = 2 },
				{ description = "2.5 天", data = 2.5 },
				{ description = "3 天", data = 3 },
				{ description = "3.5 天", data = 3.5 },
				{ description = "4 天", data = 4 },
				{ description = "5 天", data = 5 },
				{ description = "6 天", data = 6 },
				{ description = "7 天", data = 7 },
				{ description = "10 天", data = 10 },
				{ description = "11 天", data = 11 },
				{ description = "12 天", data = 12 },
				{ description = "13 天", data = 13 },
				{ description = "14 天", data = 14 },
				{ description = "15 天", data = 15 },
				{ description = "20 天", data = 20 },
				{ description = "30 天", data = 30 },
				{ description = "40 天", data = 40 },
				{ description = "50 天", data = 50 },
				{ description = "从不", data = 100000 }, --Cheat
			},
			default = 7,
		},
		{
			name    = "woose_aoedmg",
			label   = "旋转范围伤害",
			hover   = "麋鹿鹅的旋转在其范围内能造成多少伤害。",
			options = options_hundred,
			default = 3,
		},
		{
			name    = "woose_speen",
			label   = "旋转速度",
			hover   = "鹅的旋转速度有多快。",
			options =
			{
				{
					description = "0",
					data = 0,
					hover = "0 完全禁用旋转移动."
				},
				{ description = "1",  data = 1 },
				{ description = "2",  data = 2 },
				{ description = "3",  data = 3 },
				{ description = "4",  data = 4 },
				{ description = "5",  data = 5 },
				{ description = "6",  data = 6 },
				{ description = "7",  data = 7 },
				{ description = "8",  data = 8 },
				{ description = "9",  data = 9 },
				{ description = "10", data = 10 },
				{ description = "11", data = 11 },
				{ description = "12", data = 12 },
				{ description = "13", data = 13 },
				{ description = "14", data = 14 },
				{ description = "15", data = 15 },
			},
			default = 10,
		},
		{
			name    = "woose_grog",
			label   = "旋转眩晕",
			hover	= "鹅在旋转之后是多么的昏昏沉沉。",
			options =
			{
				{description = "0", data = 0,
				hover = "0 禁用昏厥"},
				{description = "1", data = 1},
				{description = "2", data = 1.2},
				{description = "3", data = 1.3},
				{description = "4", data = 1.4},
				{description = "5", data = 1.5},
			},
			default = 1,
		},
		{
			name    = "woose_iframes",
			label   = "旋转无敌",
			hover   = "为麋鹿鹅的旋转提供无敌帧。在此期间你将无敌。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = true,
		},
		{
			name    = "woose_lightn",
			label   = "旋转触电几率",
			hover   = "开始旋转时触电的几率是多少%。",
			options =
			{
				{ description = "0%",   data = 0 },
				{ description = "5%",   data = 0.05 },
				{ description = "10%",  data = 0.1 },
				{ description = "20%",  data = 0.2 },
				{ description = "30%",  data = 0.3 },
				{ description = "40%",  data = 0.4 },
				{ description = "50%",  data = 0.5 },
				{ description = "60%",  data = 0.6 },
				{ description = "70%",  data = 0.7 },
				{ description = "80%",  data = 0.8 },
				{ description = "90%",  data = 0.9 },
				{ description = "100%", data = 1 },
			},
			default = 0,
		},
		{
			name    = "woose_spinhammer",
			label   = "旋转攻击建筑物",
			hover   = "允许鹅的旋转攻击建筑物和其他可锤击物体。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = false,
		},
		--All
		Title("All","其它"),
		{
			name    = "enable_unintelligible",
			label   = "启用含糊不清的言语",
			hover   = "所有四个幼兽只能发出各种咕哝声和呱呱声。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = false,
		},
		{
			name    = "enable_monstertag",
			label   = "启用怪物标签",
			hover   = "给熊獾、鹿角怪和龙蝇增加怪物标签，使其像蜘蛛一样 使被动生物（如猪人）变为敌对。",
			options =
			{
				{ description = "是", data = true },
				{ description = "否",  data = false },
			},
			default = false,
		},
	}
}
return info