local STRINGS = GLOBAL.STRINGS

STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.MODCRASH = "%s 崩溃!"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.SUSPECTEDMODS = "可能的原因:\n"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.SUSPECTEDCONFLICTS = "可能的Mod冲突:\n"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.MODALLQUIT = "禁用所有模组"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.MODONEQUIT = "关闭模组"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.RETURNTOMENU = "返回到菜单页面"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.GAMERELOAD = "重新加载游戏"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.RECONNECT = "重新连接"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.CLIENTLOG_LOC = "客户端日志位置\n(返回到上级目录)"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.SAVEQUICKLOG = "保存精简日志\n(保存在DST的数据文件夹中)"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.SAVEDQUICKLOG = "已在DST的数据文件夹中创建精简日志"
STRINGS.UI.MAINSCREEN.BETTERCRASHSCREEN.MODPAGE = "创意工坊页面"