--Re-Gorge-itated (Client) 汉化
local STRINGS = GLOBAL.STRINGS
STRINGS.UI.REGORGESCREEN.ENTER = "进入暴食"
STRINGS.UI.REGORGESCREEN.BROWSE = "浏览服务器"
STRINGS.UI.REGORGESCREEN.RECIPES = "食谱"
STRINGS.UI.REGORGESCREEN.ACCOMPLISHMENTS = "成就"
STRINGS.UI.REGORGESCREEN.TOOLTIP_BROWSE = "浏览所有暴食服务器"
STRINGS.UI.REGORGESCREEN.TOOLTIP_RECIPES = "看看你的食谱书上有什么"
STRINGS.UI.REGORGESCREEN.TOOLTIP_ACCOMPLISHMENTS = "你的成就"
STRINGS.UI.REGORGESCREEN.SUBANDDOWNLOAD = "订阅和下载模式"
STRINGS.UI.REGORGESCREEN.UPDATE = "更新模组"
STRINGS.UI.REGORGESCREEN.CONNECTING = "连接"