local STRINGS = GLOBAL.STRINGS

-- 允许管理员在聊天栏中键入“/worldjump”以生成新世界
STRINGS.UI.BUILTINCOMMANDS.WORLDJUMP = {
	PRETTYNAME = "世界折跃",
	DESC = "激活传送基座!",
	VOTETITLEFMT = "我们应该激活传送基座吗？",
	VOTENAMEFMT = "投票激活传送基座",
	VOTEPASSEDFMT = "基座将在10秒内激活...",
}


if STRINGS.TELEPORTATOMOD==nil then
    STRINGS.TELEPORTATOMOD = {}
end

STRINGS.TELEPORTATOMOD.WORLD_JUMP = "世界折跃！"
STRINGS.TELEPORTATOMOD.WORLD_JUMP_ABORT = "世界折跃中止，因为当前世界不是主世界！"
STRINGS.TELEPORTATOMOD.WORLD_JUMP_ABORT_NOT_ENOUGH_PLAYERS =
    "世界折跃中止，因为没有足够的玩家靠近传送基座。\n需要一半以上 %u/%u"

local NUMBER = GLOBAL.TUNING.TELEPORTATOMOD.ITEMNUMBERTRANS
if NUMBER == "all" then NUMBER = "所有物品" end
STRINGS.TELEPORTATOMOD.WORLD_JUMP_TIPS = "如果你不想在15秒内进入一个新世界，请离开传送区！\n可转移的物品数："..NUMBER
STRINGS.TELEPORTATOMOD.WORLD_JUMP_TICK_5S = "还剩5秒！"
STRINGS.TELEPORTATOMOD.WORLD_JUMP_TICK_4S = "还剩4秒！"
STRINGS.TELEPORTATOMOD.WORLD_JUMP_TICK_3S = "还剩3秒！"
STRINGS.TELEPORTATOMOD.WORLD_JUMP_TICK_2S = "还剩2秒！"
STRINGS.TELEPORTATOMOD.WORLD_JUMP_TICK_1S = "还剩1秒！"
STRINGS.TELEPORTATOMOD.TELE_PICKUP = " 拿起了 "

STRINGS.TELEPORTATOMOD.TELE_COMPLETED_HEARTHAT = "基座已建造完成！你听到了吗？！"
STRINGS.TELEPORTATOMOD.TELE_COMPLETED = "基座已建造完成！"
STRINGS.TELEPORTATOMOD.TELE_MORE_THAN = "必须超过 %u 名玩家在传送点附近！\n当前人数： %u"
STRINGS.TELEPORTATOMOD.TELE_LESS_THAN = "至少 %u 名玩家必须在传送点附近！\n当前人数: %u"

STRINGS.TELEPORTATOMOD.TELE_DISABLED =
    "世界折跃已禁用。\n但是管理员/主机仍然可以在控制台中键入命令或将TUNING.TELEPORTATOMOD.TELENEWWORLD设置为true！"

STRINGS.TELEPORTATOMOD.PLAYERS_TOO_FAR_AWAY = "有人离得太远了..."
STRINGS.TELEPORTATOMOD.MAXWELL_DOOR_ENTER = "HA-HA-HA!"
STRINGS.TELEPORTATOMOD.PLAYER_REJECT_ENTER = "也许下次..."
STRINGS.TELEPORTATOMOD.DIALOG_ADV_TITLE = "冒险的大门！"
STRINGS.TELEPORTATOMOD.DIALOG_ADV_BODYTEXT =
    "你即将开始一次漫长而艰巨的探险，寻找熟悉的东西。\n你需要在五个随机选择的世界中生存下来，\n每个世界都给你带来了独特的挑战。你不会再回到这个世界了。"
STRINGS.TELEPORTATOMOD.DIALOG_ADV_GO = "我们走！"
STRINGS.TELEPORTATOMOD.DIALOG_ADV_STAY = "再等等.."

STRINGS.TELEPORTATOMOD.SUBTITLES =
{
	"序章",
	"第 1/5 章",
	"第 2/5 章",
	"第 3/5 章",
	"第 4/5 章",
	"第 5/5 章",
	"尾声",
}

STRINGS.TELEPORTATOMOD.TITLES["Maxwells Door"] = "麦斯威尔之门"
STRINGS.TELEPORTATOMOD.TITLES["A Cold Reception"] = "冷淡的接待"
STRINGS.TELEPORTATOMOD.TITLES["King of Winter"] = "冬季之王"
STRINGS.TELEPORTATOMOD.TITLES["The Game is Afoot"] = "游戏进行中"
STRINGS.TELEPORTATOMOD.TITLES["Archipelago"] = "群岛"
STRINGS.TELEPORTATOMOD.TITLES["Two Worlds"] = "两个世界"
STRINGS.TELEPORTATOMOD.TITLES["Darkness"] = "暗无天日"
STRINGS.TELEPORTATOMOD.TITLES["Checkmate"] = "挫败"